export const cardImages = [
  {
    src: "/img/farmguide/farmguideSite-part-1.jpg",
    alt: "Farmguide",
    url: "/projects/farmguide",
    badge: "Website",
    parts: "Farmguide",
  },
  {
    src: "/img/company_ads/MojorTrailors.png",
    alt: "Farmguid_Ads",
    url: "/projects/farmguide_ads",
    badge: "Design",
    parts: "Farmguide_ads",
  },
  {
    src: "/img/pageup_onboarding/Pageup_onboarding.png",
    alt: "Pageup_onboarding",
    url: "/projects/pageup_onboarding",
    badge: "Website",
    parts: "Onboarding",
  },
  {
    src: "/img/social_ads/FG-5-new.png",
    alt: "social_ads",
    url: "/projects/social_ads",
    badge: "Design",
    parts: "social_ads",
  },
  {
    src: "/img/vortex/vortex-1.jpg",
    alt: "vortex",
    url: "/projects/vortex",
    badge: "Website",
    parts: "vortex",
  },
  {
    src: "/img/TF/Home.jpg",
    alt: "tomorrow_foundation",
    url: "/projects/tomorrow_foundation",
    badge: "Website",
    parts: "TF",
  },
  {
    src: "/img/alway/Alway_Design-1.png",
    alt: "alway",
    url: "/projects/alway",
    badge: "Design",
    parts: "Alway",
  },
  {
    src: "/img/awash/about_us.jpg",
    alt: "awash",
    url: "/projects/awash",
    badge: "Website",
    parts: "Awash",
  },
  {
    src: "/img/exp/2.jpg",
    alt: "exp",
    url: "/projects/exp",
    badge: "Website",
    parts: "exp",
  },
  {
    src: "/img/gizham/page1.jpg",
    alt: "gizham",
    url: "/projects/gizham",
    badge: "Website",
    parts: "gizham",
  },
  {
    src: "/img/rst/Home1.jpg",
    alt: "rst",
    url: "/projects/rst",
    badge: "Website",
    parts: "rst",
  },
  {
    src: "/img/shiraaz/Home1.jpg",
    alt: "shiraaz",
    url: "/projects/shiraaz",
    badge: "Website",
    parts: "shiraaz",
  },
  
];